config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  constraints Clearance::Constraints::SignedIn.new do
    root to: "recipes#index", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "welcome#index"
  end

  resources :recipes, only: [:new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  validates_presence_of :name, :url, :image_url

  acts_as_taggable

  def self.filter_by_tag(tag)
    tagged_with(tag)
  end

  def self.filter_by_name(name)
    where("lower(name) LIKE :name", name: "%" + name + "%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login
  before_action :set_recipe, only: [:edit, :update, :destroy]

  def index
    @recipes = current_user.recipes
    @recipes = @recipes.filter_by_tag(params[:tag]) if params[:tag]
    @recipes = @recipes.filter_by_name(params[:name]) if params[:name]
    @recipes = @recipes.page(params[:page])

    @tags = current_user.recipes.tag_counts
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :url, :image_url, :tag_list)
  end

  def set_recipe
    @recipe = current_user.recipes.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def all_filter_tag
    render partial: "tag", locals: locals_for_all_tag
  end

  def filter_tag(tag)
    render partial: "tag", locals: locals_for_tag(tag)
  end

  def filters_applied?
    (params[:tag] || params[:name]).present?
  end

  private

  def locals_for_all_tag
    { name: "all", count: current_user.recipes.count, link: link_for_all_tag, is_active: all_tag_is_active? }
  end

  def link_for_all_tag
    request.params.except(:tag)
  end

  def all_tag_is_active?
    request.params[:tag].nil? 
  end

  def locals_for_tag(tag)
    { name: tag.name, count: tag.count, link: link_for_tag(tag), is_active: tag_is_active?(tag) }
  end

  def link_for_tag(tag)
    request.params.merge(tag: tag.name)
  end

  def tag_is_active?(tag)
    request.params[:tag] == tag.name
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<header class="flex items-center h-16 bg-gray-800 text-white">
  <div class="ml-4 uppercase tracking-wide font-bold">Recipes</div>

  <div class="ml-auto mr-4 hover:underline">
    <% if signed_in? %>
      <%= link_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-100 text-gray-900">

    <%= render "layouts/nav" %>

    <%= yield %>
  </body>
</html>

app/views/recipes/_filtered_by.html.erb
<% if filters_applied? %>
  <div class="mx-4 mt-4">
    <span class="text-xs font-bold tracking-wide uppercase">
      Filtered by:
    </span>

    <% if params[:tag] %>
      <span class="ml-2 px-2 py-1 text-sm text-gray-700 tracking-wide font-semibold rounded-full border-2 border-gray-700">
        <%= params[:tag]  %>
        <%= link_to "&times;".html_safe, request.params.except(:tag) %>
      </span>

    <% end %>

    <% if params[:name].present? %>
      <span class="ml-2 px-2 py-1 text-sm text-gray-700 tracking-wide font-semibold rounded-full border-2 border-gray-700">
        <%= params[:name]  %>
        <%= link_to "&times;".html_safe, request.params.except(:name, :commit) %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/recipes/_form.html.erb
<%= form_for recipe do |form| %>
  <div>
    <ul class="text-red-700">
      <% recipe.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>

  <div class="mt-4 grid gap-4">
    <div class="flex flex-col">
      <%= form.label :name, class: "font-semibold text-gray-800" %>
      <%= form.text_field :name, class: "w-full mt-2 px-4 py-1 bg-gray-200 rounded focus:bg-white focus:shadow-outline"%>
    </div>

    <div class="flex flex-col">
      <%= form.label :url, class: "font-bold text-gray-800" %>
      <%= form.text_field :url, class: "w-full mt-2 px-4 py-1 bg-gray-200 rounded focus:bg-white focus:shadow-outline"%>
    </div>

    <div class="flex flex-col">
      <%= form.label :image_url, class: "font-bold text-gray-800" %>
      <%= form.text_field :image_url, class: "w-full mt-2 px-4 py-1 bg-gray-200 rounded focus:bg-white focus:shadow-outline"%>
    </div>

    <div class="flex flex-col">
      <%= form.label :tag_list, class: "font-bold text-gray-800" %>
      <%= form.text_field :tag_list, class: "w-full mt-2 px-4 py-1 bg-gray-200 rounded focus:bg-white focus:shadow-outline"%>
    </div>
  </div>

  <div class="flex justify-between items-center mt-6">
    <%= form.submit class: "px-4 py-2 bg-gray-700 text-white rounded hover:bg-gray-800 hover:cursor-pointer" %>

    <%= link_to "Back", root_path, class: "hover:underline" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id=<%= dom_id(recipe) %> class="flex py-2">
  <%= image_tag recipe.image_url, alt: recipe.name, size: "128x128", class: "rounded" %>

  <div class="flex flex-col ml-4">
    <h3>
      <%= link_to recipe.name, recipe.url, class: "text-xl font-semibold hover:underline", target: "_blank" %>
    </h3>

    <ul class="flex gap-2 mt-2">
      <% recipe.tags.each do |tag| %>
        <li class="px-2 bg-gray-200 rounded-full">
          <%= tag %>
        </li>
      <% end %>
    </ul>

    <div class="mt-auto">
      <%= link_to "Edit", edit_recipe_path(recipe), class: "hover:underline" %> |
      <%= link_to "Delete", recipe, method: :delete, class: "hover:underline" %>
    </div>
  </div>
</div>

app/views/recipes/_search.html.erb
<%= form_tag root_path, method: :get, id: "search", class: "w-full" do %>
  <%= text_field_tag "tag", params[:tag], hidden: true, disabled: params[:tag].nil? %>
  <div class="flex w-full">
    <%= text_field_tag "name", nil, class: "w-full px-4 py-2 rounded shadow focus:shadow-outline", placeholder: "Search..." %>
  </div>

  <button class="hidden"></button>
<% end %>

app/views/recipes/_tag.html.erb
<div class="px-4 py-1 text-sm <%= is_active ? 'text-gray-800' : 'text-gray-500' %> hover:text-gray-800 font-semibold hover:bg-gray-200 rounded">
  <%= link_to link do %>
    <span>
      <%= name %>
    </span>
    <span class="text-xs text-gray-500">
      (<%= count %>)
    </span>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<div class="w-full max-w-md mx-auto mt-8 p-4 bg-white rounded shadow">
  <h1 class="text-lg text-gray-800 font-semibold">Edit Recipe</h1>

  <%= render "form", recipe: @recipe %>
</div>

app/views/recipes/index.html.erb
<div class="flex w-full max-w-screen-lg px-4 mx-auto">
  <div class="mt-4 w-1/5">
    <h1 class="text-lg text-gray-800 font-semibold">My Recipes</h1>

    <div class="mt-4">
      <h2 class="text-sm tracking-wide font-bold uppercase text-gray-600">Tags</h2>

      <div class="mt-2 pr-4">
        <%= all_filter_tag %>

        <% @tags.each do |tag| %>
          <%= filter_tag tag %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="mt-4 w-4/5">
    <div class="flex items-center space-x-4 w-full">
      <%= render "recipes/search" %>
      <%= link_to "New Recipe", new_recipe_path, class: "flex-shrink-0 px-4 py-2 text-gray-700 font-semibold tracking-wide border-2 border-gray-700 hover:bg-gray-700 hover:text-white rounded" %>
    </div>

    <%= render "recipes/filtered_by" %>

    <div class="divide-y mt-6 px-4 py-2 rounded shadow bg-white">
      <% if @recipes.empty? %>
        <p class="w-full text-center text-gray-500 text-lg font-bold tracking-wide">No recipes here...</p>
      <% else %>
        <%= render @recipes %>
        <%= paginate @recipes %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="w-full max-w-md mx-auto mt-8 p-4 bg-white rounded shadow">
  <h1 class="text-lg text-gray-800 font-semibold">New Recipe</h1>

  <%= render "form", recipe: @recipe %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |form| %>
  <div class="mt-4 grid gap-4">
    <div class="flex flex-col">
      <%= form.label :email, class: "font-semibold text-gray-800" %>
      <%= form.email_field :email, class: "w-full mt-2 px-4 py-1 bg-gray-200 rounded focus:bg-white focus:shadow-outline"%>
    </div>

    <div class="flex flex-col">
      <%= form.label :password, class: "font-semibold text-gray-800" %>
      <%= form.password_field :password, class: "w-full mt-2 px-4 py-1 bg-gray-200 rounded focus:bg-white focus:shadow-outline"%>
    </div>


    <div class="flex justify-between items-center mt-6">
      <%= form.submit class: "px-4 py-2 bg-gray-700 text-white rounded hover:bg-gray-800 hover:cursor-pointer" %>

      <div class="other-links">
          <%= link_to t(".sign_in"), sign_in_path, class: "hover:underline" %>
      </div>
    </div>

  </div>
<% end %>

app/views/users/new.html.erb
<div class="w-full max-w-md mx-auto mt-8 p-4 bg-white rounded shadow">
  <h1 class="text-lg text-gray-800 font-semibold">Sign up</h1>

  <%= render partial: '/users/form' %>
</div>

app/views/welcome/index.html.erb
<h1>Recipes</h1>
<p>The time is <time><%= Time.now %></time></p>